import React, {Component} from 'react';
import {render} from 'react-dom';
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Fitting AI
        </h1>

        <p className={styles.description}>
          <Link href = "/second-page">
	  <button>
	  <a>仮想試着を始める</a>
	  </button>
	  </Link>
        </p>


      </main>

      <footer className={styles.footer}>
          Powered by 衣服知能株式会社
      </footer>
    </div>
  )
}
